name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🔥 Breaking Changes'
    labels:
      - 'breaking'
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
  - title: '👋 Deprecated'
    labels:
      - 'deprecation'
  - title: '🔗 Dependency Updates'
    labels:
      - 'library-update'
      - 'dependencies'
  - title: '🛠  Internal Updates'
    labels:
      - 'internal'
      - 'kaizen'
      - 'test-library-update'
      - 'sbt-plugin-update'
  - title: '📚 Docs'
    labels:
      - 'doc'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION


autolabeler:
  - label: 'doc'
    files:
      - '*.md'
  - label: 'feature'
    title:
      - '/(support|add)/i'
  - label: 'bug'
    title:
      - '/fix/i'
  - label: 'internal'
    title:
      - '/internal/i'
  - label: 'deprecation'
    title:
      - '/deprecate/i'
