addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype"    % "2.3")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"         % "2.0.0-M2")
addSbtPlugin("com.github.sbt"    % "sbt-findbugs"    % "2.0.0")
addSbtPlugin("com.github.sbt"    % "sbt-jacoco"      % "3.0.3")
addSbtPlugin("org.xerial.sbt"    % "sbt-jcheckstyle" % "0.2.0")
addSbtPlugin("com.typesafe.sbt"  % "sbt-osgi"        % "0.9.2")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.4.0")
addSbtPlugin("com.dwijnand"      % "sbt-dynver"      % "3.3.0")

scalacOptions ++= Seq("-deprecation", "-feature")
