name: Release Note

on:
  push:
    tags:
      - v*
  workflow_dispatch:      

jobs:
  release:
    name: Create a new release note
    runs-on: ubuntu-latest
    steps:         
      - name: Create a release note
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "$GITHUB_REF_NAME" --repo="$GITHUB_REPOSITORY" --generate-notes
